--cities
INSERT INTO cities (zip_code, name) VALUES (1920,'Martigny')
INSERT INTO cities (zip_code, name) VALUES (3960,'Sierre')
INSERT INTO cities (zip_code, name) VALUES (1950,'Sion')
INSERT INTO cities (zip_code, name) VALUES (3963,'Montana')
INSERT INTO cities (zip_code, name) VALUES (3966,'Chalais')
INSERT INTO cities (zip_code, name) VALUES (1964,'Conthey')
INSERT INTO cities (zip_code, name) VALUES (1955,'Chamoson')
INSERT INTO cities (zip_code, name) VALUES (1926,'Fully')

--restaurants
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Café de la Gare',2)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Café du coin',3)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Pizzeria Italia',4)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Irish Pub',5)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Fat Food',6)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Ali-Baba Kebap',7)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Swiss Meat',8)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Before Burgers',1)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Pizza Karim',2)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Ali Burgers',3)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Fish from Valais',4)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Le Cheval Blanc',5)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Café du vigneron',6)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Pizzeria Familia',7)
INSERT INTO restaurants (merchant_name, fk_cities) VALUES ('Chinese Fast Foot',8)

--dishes
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (1,'Pizza Jambon',18,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (1,'Penne Morilles',21,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (2,'Jambon Frites',15,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (2,'Cheesburger',11,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (3,'Gâteau fromage et salade',15,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (3,'Tranche panée frites',15,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (4,'Pizza Jambon',16,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (4,'Pizza Hawaii',19,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (5,'Hamburger',12,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (5,'Cheesburger',14,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (6,'Cheesburger',9,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (6,'Frites',4,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (7,'Durum',10,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (7,'Kebap Box',15,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (8,'Entrecôte CH',40,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (8,'Filet agneau GB',25,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (9,'Cheesburger',9,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (9,'Hamburger',8,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (10,'Pizza carbonara',14,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (10,'Pizza Jambon',11,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (11,'Hamburger',14,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (11,'Cheesburger',16,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (12,'Filet de truite VS',27,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (12,'Riz',3,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (13,'Steak haché - frites',14,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (13,'Steak de bœuf - frites',16,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (14,'Burger du vigneron',25,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (14,'Emincé bœuf sauce vin',30,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (15,'Pizza Jambon',19,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (15,'Pizza 4 fromages',20,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (16,'Rouleaux de printemps',16,1)
INSERT INTO dishes (fk_restaurants,name,price,status) VALUES (16,'Poulet au citron',20,1)

--customers
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('sylvain.meyer','Pass1234','Sylvain Meyer',2)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('david.crittin','Pass1234','David Crittin',1)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('robin.gallay','Pass1234','Robin Gallay',3)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('samuel.wenger','Pass1234','Samuel Wenger',4)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('louise.bretz','Pass1234','Louise Bretz',5)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('albain.dufils','Pass1234','Albain Dufils',6)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('alain.duc','Pass1234','Alain Duc',7)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('anne.lecalve','Pass1234','Anne Le Calve',8)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('yann.bocchi','Pass1234','Yann Bocchi',1)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('xavier.barmaz','Pass1234','Xavier Barmaz',2)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('david.russo','Pass1234','David Russo',3)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('jluc.beuchat','Pass1234','Jean-Luc Beuchat',4)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('nicole.glassey','Pass1234','Nicole Glassey',5)
INSERT INTO customers (username,password,full_name,fk_cities) VALUES ('jpierre.rey','Pass1234','Jean-Pierre Rey',6)

--deliverers
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('lucas.lopez','1234Pass','Lucas Lopez',2)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('james.bonvin','1234Pass','James Bonvin',1)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('steven.varone','1234Pass','Steven Varone',3)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('pierre.fumeaux','1234Pass','Pierre Fumeaux',4)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('josiane.salamin','1234Pass','Josiane Salamin',5)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('leonie.farquet','1234Pass','Léonie Farquet',6)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('olivier.clausen','1234Pass','Olivier Clausen',7)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('melissa.lee','1234Pass','Mélissa Lee',2)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('joe.darbellay','1234Pass','Joé Darbellay',1)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('megane.depreux','1234Pass','Mégane De Preux',2)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('jose.ferreira','1234Pass','José Ferreira',3)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('albert.constantin','1234Pass','Albert Constantin',4)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('lea.gay','1234Pass','Léa Gay',5)
INSERT INTO deliverers (username,password,full_name,fk_cities) VALUES ('noel.barmaz','1234Pass','Noël Barmaz',6)

--orders_status
INSERT INTO orders_status (status) VALUES ('Commande reçue')
INSERT INTO orders_status (status) VALUES ('Commande en cours de préparation')
INSERT INTO orders_status (status) VALUES ('Commande en cours de livraison')
INSERT INTO orders_status (status) VALUES ('Commande livrée')
INSERT INTO orders_status (status) VALUES ('Commande annulée')

--orders
INSERT INTO orders (fk_customers,fk_deliverers,delivery_time_requested) VALUES(2,2,CURRENT_TIMESTAMP)
INSERT INTO orders (fk_customers,fk_deliverers,delivery_time_requested) VALUES(3,3,CURRENT_TIMESTAMP)

--order_dishes
INSERT INTO order_dishes (fk_orders,fk_dishes,quantity) VALUES(1,10,2)
INSERT INTO order_dishes (fk_orders,fk_dishes,quantity) VALUES(1,11,2)
INSERT INTO order_dishes (fk_orders,fk_dishes,quantity) VALUES(2,4,3)

--orders_status_history
INSERT INTO orders_status_history(fk_orders,fk_orders_status,created_at) VALUES(1,1,CURRENT_TIMESTAMP)
INSERT INTO orders_status_history(fk_orders,fk_orders_status,created_at) VALUES(1,2,CURRENT_TIMESTAMP)
INSERT INTO orders_status_history(fk_orders,fk_orders_status,created_at) VALUES(1,3,CURRENT_TIMESTAMP)
INSERT INTO orders_status_history(fk_orders,fk_orders_status,created_at) VALUES(2,1,CURRENT_TIMESTAMP)
